### ISSUE TITLE
Ordering / sorting

### ISSUE THREAD

**Issue by eusi** [schuhwerk/php-error-log-viewer#10]
Hi,

Very nice error log reader. The only thing that drives me crazy a bit is the sorting.

Even in your screenshot the sorting looks weird (at least I don't understand it =):
https://raw.githubusercontent.com/schuhwerk/php-error-log-viewer/master/screenshot.png

**Lets imagine this list in the screenshot would be sorted for time** (even in the screenshots looks like sorted by "count", but the counts are not sorted obviously):

See the time of the red error, which is 12:31. However one line below there is a time of 11:45. 
I guess your idea is probably that you keep the log-messages at the same position, but you increase the counter and update its time only.

However, I would prefer to have the entries always sorted by time. So I would expect to have the 12:31 as the last one. If the same errors happens 5min later, then this error should be again the last one (and its time should be updated and counter should be incremented as usual).

Is this possible?

Reason:
If you have one error which occurred at beginning of the list, but happens afterwards a lot of times again, you will not recognize this one. Recently I had one and I only recognized it "accidentally" when I scrolled up and then I saw its count at "80" :-/

Thanks a lot!
eusi

**Comment by schuhwerk** [comment]
Hi! Thanks for your feedback! I took a while to come back to this issue... Can you check if this still happens in the most recent release?

**Comment by eusi** [comment]
Tested and it looks good, thank you! :-)
