### ISSUE TITLE
Nginx "error.log"

### ISSUE THREAD

**Issue by emresaracoglu** [schuhwerk/php-error-log-viewer#11]
Hi,

I guess Nginx is not compatible with `error.log` file. Because I can't see any errors on the screen. 

```
2022/01/04 11:48:38 [error] 19611#19611: *1340 FastCGI sent in stderr: "PHP message: PHP Warning:  session_destroy(): Trying to destroy uninitialized session in /var/w......./......./Ping.php on line 52" while reading response header from upstream, client: 123.456.789.012, server: sub.example.com, request: "POST /.../Ping HTTP/2.0", upstream: "fastcgi://unix:/var/lib/php7.3-fpm/web4.sock:", host: "pro.krokexam.com", referrer: "https://sub.example.com/page?id=content"
```

Could it be compatible with this in the future?

**Comment by schuhwerk** [comment]
Hi! Thanks for your feedback! The logger does not support Nginx-logs at the moment (I also added this information to the readme).
I don't have plans to implement that, but I'm happy to accept PRs considering this issue!
