### ISSUE TITLE
error on php 8.2 and 8.3

### ISSUE THREAD

**Issue by irulvam** [schuhwerk/php-error-log-viewer#15]
hi. some code has deprecated. please update for new PHP

Deprecated: Creation of dynamic property Php_Error_Log_Viewer\AjaxHandler::$log_handler is deprecated in /var/www/logviewer/src/AjaxHandler.php on line 17

**Comment by andymoyle** [comment]
I had the same deprecation notice.You can fix by adding 
public $log_handler;
to src/AjaxHandler.php before public function __construct

```
class AjaxHandler
{
    public $log_handler;
public function __construct($log_handler)
    {
        $this->log_handler = $log_handler;
    }
```

**Comment by schuhwerk** [comment]
Closed in https://github.com/schuhwerk/php-error-log-viewer/commit/6204f2c6e16f8493cfceb7f402ec7327cab24480. Thanks!
