### ISSUE TITLE
Sort by Time does not work

### ISSUE THREAD

**Issue by eusi** [schuhwerk/php-error-log-viewer#3]
Hi, 
First of all, cool viewer, thanks for that!
However I have one issue.

**Issue:**
Sorting by Time does not work on my side.

**My goal:** 
By default, when the viewer is opened, the new entries should be always on top (with other words: original debug.log-list just up side down). Also if new messages appear, they should appear on top.

**Side facts:**
Sorting by Count or Message works as expected.
My php.log entries format look like that:
[13-Jun-2021 10:30:08 Europe/Berlin] WARNING: ...
[13-Jun-2021 10:30:08 Europe/Berlin] INFO: ...
[13-Jun-2021 10:30:08 Europe/Berlin] ERROR: ...

Greetz
eusi

**Comment by schuhwerk** [comment]
Hi! You are welcome :)
Thanks for your feedback!
I found time to fix the issue today: https://github.com/schuhwerk/php-error-log-viewer/commit/5fa3a58d1583aced1d9ba6b8fc8dd3de90591507

Cheers from Cologne!
