### ISSUE TITLE
reaload / refresh don't keep sorting

### ISSUE THREAD

**Issue by fglueck** [schuhwerk/php-error-log-viewer#7]
After refresh is the sorting missing, eg. if you sort by time descending to see the newest entries, this is lost.

**Comment by schuhwerk** [comment]
Great catch! Thank you :)
This looks like an issue with the vue-material library. It might be an issue, which was introduced in a newer version (the initial sorting is not working any more).
To avoid this issue I just added sorting before passing it to vue-material here: https://github.com/schuhwerk/php-error-log-viewer/commit/3451eedf0afd11e5ca6d71ad177a2ba9c03e6077
