### ISSUE TITLE
 ($length) must be greater than 0

### ISSUE THREAD

**Issue by fglueck** [schuhwerk/php-error-log-viewer#8]
PHP Fatal error:  Uncaught ValueError: fread(): Argument #2 ($length) must be greater than 0 in /srv/www/html/cockpit/public/intern/log/index.php:101
Stack trace:
#0 /srv/www/html/cockpit/public/intern/log/index.php(101): fread()
#1 /srv/www/html/cockpit/public/intern/log/index.php(223): Pelv_Log_Handler->get_file()
#2 /srv/www/html/cockpit/public/intern/log/index.php(75): Pelv_Log_Handler->ajax_json_log()
#3 /srv/www/html/cockpit/public/intern/log/index.php(19): Pelv_Log_Handler->handle_ajax_requests()
#4 {main}
  thrown in /srv/www/html/cockpit/public/intern/log/index.php on line 101

I think it comes if file allready in access / currently written...

**Comment by schuhwerk** [comment]
Thanks for your feedback! I just improved the ``fread()`` - handling. Can you check if https://github.com/schuhwerk/php-error-log-viewer/commit/13c0534017a771554d841e19f66d4b0db2481d78 fixes this (by pulling the newest master)?

**Comment by fglueck** [comment]
currently it looks good, since the last hours, no errors

**Comment by eusi** [comment]
When the file was empty I got the same error. With your fix it seems to be fixed, thanks :-)
